### ISSUE TITLE
Game crash with OnWndProc issue

### ISSUE THREAD

**Issue by kinggreedy** [EnsageSharp/Ensage.Release#2]
Hi, Today I just find out a strange behavior with Game.OnWndProc and Drawing.OnDraw. If I attach Drawing.OnDraw += Drawing_OnDraw and I don't attach Game.OnWndProc += Empty_Function, and no other script with Game.OnWndProc += ... is running, and I refresh E#, game will crash.

Step to Reproduce:

1. Write a script with only Drawing.OnDraw += Any_Function_1 in main
2. Untick all other scripts, only new script and Ensage.Common
3. Start the game and wait for E# to Inject
4. Play Demo hero
5. Press F5 to reinject E#

Expected: Script reloaded
Got: Crash

Step to Workaround:

1. Append Game.OnWndProc += Empty_Function or tick 1 assembly with Game.OnWndProc
2. Continue with step 3 from above

Expected: Script reloaded
Got: Script reloaded, work as intended.

**Comment by Rulfy** [comment]
It's a problem with the sandbox. I already told h3h3 to fix it, but he's currently not available, so that we've to wait for his update/return.
