### ISSUE TITLE
BUG: Game.PrintMessage(); 6.86

### ISSUE THREAD

**Issue by kivlara** [EnsageSharp/Ensage.Release#3]
Hi,

I try to:
```
Game.PrintMessage("<font face='Verdana' color='#ff7700'>TEST OK!</font>", MessageType.ChatMessage);
```

No message is show.
Other chat messages disappear. 

UPDATE: I moved this issue from common to this repo.

**Comment by judge2020** [comment]
you already posted this: https://github.com/EnsageSharp/Ensage.Common/issues/12

post on the dev section of the forum, not here

**Comment by kivlara** [comment]
Sorry, I write this on forum too, but I think github is made for this, and all developers are familiar with it.
